CREATE TABLE CAMPEONATO(

Llave VARCHAR(6) NOT NULL UNIQUE,
Nombre VARCHAR(30) NOT NULL ,
Fecha_de_inicio DATE NOT NULL ,
Hora_de_inicio TIME NOT NULL,
Fecha_de_fin DATE NOT NULL ,
Hora_de_fin TIME NOT NULL,
Descripcion_de_reglas VARCHAR(1000),
PRIMARY KEY(Llave));


CREATE TABLE PAISES(
Nombre VARCHAR(30) NOT NULL UNIQUE,
PRIMARY KEY (Nombre));
 

CREATE TABLE CARRERA(
Nombre VARCHAR(30) NOT NULL,
Pais VARCHAR(30) NOT NULL,
Estado int NOT NULL,
Nombre_de_pista VARCHAR(30) NOT NULL,
Fecha_de_inicio DATE NOT NULL,
Hora_de_inicio TIME NOT NULL,
Fecha_de_fin DATE NOT NULL,
Hora_de_fin TIME NOT NULL,
Campeonato_key VARCHAR(6) NOT NULL,
PRIMARY KEY (Nombre, Campeonato_key),
FOREIGN KEY (Campeonato_key) REFERENCES CAMPEONATO (Llave),
FOREIGN KEY (Pais) REFERENCES PAISES (Nombre));


INSERT INTO "PAISES"
VALUES ('FRANCIA');
INSERT INTO "PAISES"
VALUES ('ESPAÑA');
INSERT INTO "PAISES"
VALUES ('PORTUGAL');
INSERT INTO "PAISES"
VALUES ('ARABIA SAUDI');


INSERT INTO "CAMPEONATO"
VALUES ('QWE123','GP de ARABIA SAUDI',  '2022-03-25', '00:00:00', '2022-03-27', '9:00:00', 'Ver reglas');

INSERT INTO "CARRERA"
VALUES ('Street Circuit', 'ARABIA SAUDI',0,'Jeddah', '2022-03-26', '17:00:00', '2022-03-27', '4:00:00', 'QWE123');